// Estilos centralizados para la aplicación
import { C } from '../constants/colors'

export const S = {
  app: {
    minHeight:       '100vh',
    background:      C.background,
    display:         'flex',
    flexDirection:   'column' as const,
    alignItems:      'center',
    padding:         '24px 16px 48px',
    gap:             '0px',
    fontFamily:      "'Press Start 2P', monospace",
    position:        'relative' as const,
    overflow:        'hidden',
  },
  scanlines: {
    position:        'fixed' as const,
    inset:           0,
    pointerEvents:   'none' as const,
    zIndex:          9999,
    backgroundImage: `repeating-linear-gradient(0deg, ${C.foreground} 0px, transparent 1px, transparent 3px)`,
    opacity:         0.04,
  },
  title: {
    color:           C.primary,
    fontSize:        '13px',
    letterSpacing:   '1px',
    marginBottom:    '20px',
    textShadow:      `2px 2px 0 ${C.grey700}`,
  },
  panel: {
    width:           '100%',
    maxWidth:        '660px',
    background:      C.surface,
    border:          `3px solid ${C.borderStrong}`,
    boxShadow:       `4px 4px 0 ${C.grey700}`,
    padding:         '20px',
    marginBottom:    '0px',
  },
  label: {
    display:         'block',
    color:           C.muted,
    fontSize:        '8px',
    marginBottom:    '8px',
    letterSpacing:   '1px',
  },
  select: {
    width:           '100%',
    background:      C.background,
    color:           C.foreground,
    border:          `3px solid ${C.borderStrong}`,
    boxShadow:       `3px 3px 0 ${C.grey700}`,
    padding:         '10px 12px',
    fontFamily:      "'Press Start 2P', monospace",
    fontSize:        '8px',
    borderRadius:    '0',
    cursor:          'pointer',
    appearance:      'none' as const,
    WebkitAppearance:'none' as const,
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpolygon points='0,0 12,0 6,8' fill='%23484f58'/%3E%3C/svg%3E")`,
    backgroundRepeat:'no-repeat',
    backgroundPosition:'calc(100% - 12px) 50%',
    paddingRight:    '32px',
  },
  selectRow: {
    display:         'grid',
    gridTemplateColumns: '1fr 1fr',
    gap:             '20px',
    marginBottom:    '0',
  },
  divider: {
    width:           '100%',
    maxWidth:        '660px',
    height:          '4px',
    background:      `repeating-linear-gradient(90deg, ${C.grey700} 0px, ${C.grey700} 8px, transparent 8px, transparent 16px)`,
    margin:          '0',
  },
  confirmPanel: {
    width:           '100%',
    maxWidth:        '660px',
    background:      C.surface,
    border:          `3px solid ${C.borderStrong}`,
    boxShadow:       `4px 4px 0 ${C.grey700}`,
    padding:         '20px',
  },
  confirmGrid: {
    display:         'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap:             '16px',
    marginBottom:    '20px',
  },
  confirmLabel: {
    color:           C.muted,
    fontSize:        '7px',
    marginBottom:    '6px',
    display:         'block',
    letterSpacing:   '1px',
  },
  confirmValue: {
    color:           C.foreground,
    fontSize:        '8px',
    lineHeight:      '1.6',
  },
  montoDisplay: {
    color:           C.success,
    fontSize:        '14px',
    border:          `2px solid ${C.success}`,
    padding:         '10px 16px',
    display:         'inline-block',
    boxShadow:       `3px 3px 0 ${C.grey700}`,
  },
  btnTransfer: {
    width:           '100%',
    padding:         '14px',
    background:      C.green600,
    color:           C.white,
    border:          `4px solid ${C.grey700}`,
    boxShadow:       `4px 4px 0 ${C.grey700}`,
    fontFamily:      "'Press Start 2P', monospace",
    fontSize:        '10px',
    cursor:          'pointer',
    letterSpacing:   '1px',
    borderRadius:    '0',
    transition:      'background 0.08s, transform 0.08s, box-shadow 0.08s',
  },
  btnTransferDisabled: {
    background:      C.disabledBg,
    color:           C.disabledFg,
    cursor:          'not-allowed',
    boxShadow:       'none',
  },
  successScreen: {
    width:           '100%',
    maxWidth:        '660px',
    background:      C.successSoft,
    border:          `3px solid ${C.success}`,
    boxShadow:       `4px 4px 0 ${C.grey700}`,
    padding:         '32px 24px',
    textAlign:       'center' as const,
  },
  gamePanelWrapper: {
    width:      '100%',
    maxWidth:   '660px',
    border:     `3px solid ${C.borderStrong}`,
    boxShadow:  `4px 4px 0 ${C.grey700}`,
    background: C.greyBlue900,
    overflow:   'hidden' as const,
    position:   'relative' as const,
  },
  gamePanelHeader: {
    background:     C.surface,
    borderBottom:   `2px solid ${C.border}`,
    padding:        '8px 14px',
    display:        'flex',
    justifyContent: 'space-between',
    alignItems:     'center',
  },
  gameInstructions: {
    background:   C.surface,
    borderTop:    `2px solid ${C.border}`,
    padding:      '8px 14px',
    display:      'flex',
    gap:          '24px',
  },
  gameLabel: {
    color:        C.muted,
    fontSize:     '7px',
    letterSpacing:'1px',
  },
  gameMonto: {
    color:        C.warning600,
    fontSize:     '10px',
  },
  instructionText: {
    color:        C.muted,
    fontSize:     '6px',
    letterSpacing:'1px',
  },
  dangerText: {
    color:        C.error600,
    fontSize:     '6px',
    letterSpacing:'1px',
  },
  errorMsg: {
    marginTop:    '12px',
    color:        C.danger,
    fontSize:    '7px',
    letterSpacing:'1px',
  },
}